// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC63rkF8eZyT08SOUCYnH-uovP1j9cxTGk',
    appId: '1:336536190592:web:83a9f4ac9cd9f82626f065',
    messagingSenderId: '336536190592',
    projectId: 'ecommerce-e4967',
    authDomain: 'ecommerce-e4967.firebaseapp.com',
    storageBucket: 'ecommerce-e4967.firebasestorage.app',
    measurementId: 'G-HREJ8GLRRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxzljokYfUH367-dZujDv1L57UkJ56VPE',
    appId: '1:336536190592:android:23d0e06789699ebd26f065',
    messagingSenderId: '336536190592',
    projectId: 'ecommerce-e4967',
    storageBucket: 'ecommerce-e4967.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC63rkF8eZyT08SOUCYnH-uovP1j9cxTGk',
    appId: '1:336536190592:web:3f9e83a64ab1ea3d26f065',
    messagingSenderId: '336536190592',
    projectId: 'ecommerce-e4967',
    authDomain: 'ecommerce-e4967.firebaseapp.com',
    storageBucket: 'ecommerce-e4967.firebasestorage.app',
    measurementId: 'G-51YGPB410D',
  );
}
